## Import numpy library

In [45]:
import numpy as np
from scipy import stats

## Creating Arrays
ใช้สร้างข้อมูลตัวเลขให้อยู่ในรูปแบบ Array
ซึ่งเป็นรูปแบบพื้นฐานที่ใช้เก็บ Features, Targets
และค่าต่าง ๆ ที่ใช้ในการคำนวณของ Machine Learning

In [21]:
np.zeros(10) # ใช้เมื่อเราต้องการสร้าง Array ที่เริ่มต้นด้วยค่า 0 เป็นจำนวน 10 ตัว

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.ones(10) # ใช้เมื่อเราต้องการสร้าง Array ที่ทุกตำแหน่งมีค่าเป็น 1 เป็นจำนวน 10 ตัว

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.full(10, 2.5)  # ใช้เมื่อเราต้องการกำหนดค่าเริ่มต้นเหมือนกันทุกตำแหน่ง โดยทำการสร้าง array ที่มีค่า 2.5 เป็นจำนวน 10 ตัว

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [24]:
a = np.array([1,2,3,5,7,12]) # ใช้แปลง Python List ให้เป็น NumPy Array เพื่อให้นำไปคำนวณได้ง่ายขึ้น
a # แสดงผลข้อมูล array a

array([ 1,  2,  3,  5,  7, 12])

In [25]:
np.arange(3, 10)  # ใช้สร้างตัวเลขเป็นลำดับ เช่น 3, 4, 5, ... , 9

array([3, 4, 5, 6, 7, 8, 9])

In [26]:
np.linspace(0, 100, 11) # ใช้สร้างค่าหลายค่าที่มีระยะห่างเท่ากัน ภายในช่วงที่กำหนด โดยทำการสร้าง array ตั้งแต่ 0 - 100 เป็นจำนวน 11 ตัว ทีมีระยะห่างเท่ากัน

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multi-Dimensional Arrays
ใช้สร้างข้อมูลในรูปแบบ Matrix ซึ่งคล้ายกับ Dataset หรือ DataFrame โดย
* Rows    = Samples
* Columns = Features

ใน Machine Learning นั้น Matrix มักใช้แทนข้อมูลหลาย Samples และหลาย Features

In [24]:
np.zeros((5,2)) # # สร้าง Matrix ที่มี 5 Rows และ 2 Columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]) # ทำการสร้าง Matrix 2 มิติ ที่มี 3 Rows และ 3 Columns

n # แสดงผล matrix n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
n[0, 1] = 20 # เลือกตำแหน่ง Row ที่ 1 และ Column 2 ทำการเปลี่ยนค่าจาก 2 เป็น 20

n # แสดงผล matrix n ใหม่

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [37]:
n[2] = [1,1,1]  # เลือก Row ที่ 3 แล้วทำการเปลี่ยนค่า เป็น 1 ทั้ง 3 ตัว

n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  1]])

In [36]:
n[:, 2] = [0,1,2] # ใลือก column ที่ 3 แล้วทำการเปลี่ยนค่าเป็น 0,1,2

n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

#Randomly Generated Arrays
สามารถใช้สร้างข้อมูลแบบสุ่มสำหรับการทดลอง
หรือสร้างข้อมูลตัวอย่างสำหรับทดสอบ Code

In [3]:
np.random.seed(2)
100 * np.random.rand(5, 2) # สร้างตัวเลขสุ่มในรูปแบบ Matrix

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [4]:
np.random.seed(2)
np.random.randn(5,2) # สร้างข้อมูลสุ่มที่มีการกระจายแบบ Normal Distribution

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [5]:
np.random.seed(5)
np.random.randint(low=0, high=100, size=(5,2)) # สร้างจำนวนเต็มแบบสุ่มเพื่อใช้ในการสร้างข้อมูลตัวอย่างสำหรับการทดลอง โดยสร้าง Matrix ที่มี 5 rows และ 2 column ทีมีค่าอยู่ระหว่าง 0-100

array([[99, 78],
       [61, 16],
       [73,  8],
       [62, 27],
       [30, 80]])

# Element-wise Operations
ใช้คำนวณกับทุกค่าของ Array พร้อมกัน โดยไม่ต้องเขียน Loop ทีละค่า

โดยใช้ในการคำนวณกับทุก Element ของ Array ได้พร้อมกัน และใช้บ่อยในการแปลงหรือคำนวณ Features

In [6]:
a = np.arange(5) # ทำการสร้าง array เป็นจำนวน 5 ตัว
a

array([0, 1, 2, 3, 4])

In [7]:
b = (10 +(a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [8]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

# Comparison Operations
ใช้ตรวจสอบว่าข้อมูลแต่ละค่าตรงกับเงื่อนไขหรือไม่และสามารถใช้เลือกเฉพาะข้อมูลที่เราต้องการได้ โดยจะทำการตรวจสอบทุกค่าใน Array
และแสดงผลลัพธ์จะเป็น True หรือ False


In [18]:
print(a)
print(b)
a >= 2 # สมาชิกของ array a นั้น ทีค่าใดบ้างมีค่า >= 2

[0 1 2 3 4]
[1.   1.44 1.96 2.56 3.24]


array([False, False,  True,  True,  True])

In [17]:
print(a)
print(b)
a > b # สมาชิกของ array a นั้นทีค่าใดบ้างมีค่า array b

[0 1 2 3 4]
[1.   1.44 1.96 2.56 3.24]


array([False, False,  True,  True,  True])

In [16]:
print('a',a)
print('b',b)
a[a > b] # สมาชิกของ array a นั้นทีค่าใดบ้างมีค่า array b

a [0 1 2 3 4]
b [1.   1.44 1.96 2.56 3.24]


array([2, 3, 4])

# Summarizing Operations
ใช้ดูภาพรวมของข้อมูล เช่น การกระจายของข้อมูลหรือค่าต่ำสุด

In [20]:
x = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [43]:
x.mean() # หาค่าเฉลี่ยของข้อมูล และช่วยตรวจสอบ Scale ของข้อมูล

np.float64(50.0)

In [28]:
np.median(x)  # หาค่ากลางของข้อมูลเมื่อเรียงจากน้อยไปมาก เพราะได้รับผลกระทบจากค่าผิดปกติน้อยกว่า Mean

np.float64(50.0)

In [47]:
stats.mode(x) # ค่าที่เกิดบ่อยที่สุดในข้อมูล

ModeResult(mode=array([10, 20, 30]), count=array([1, 1, 1]))

In [30]:
x.std() # ใช้ดูว่าข้อมูลกระจายออกจากค่าเฉลี่ยมากน้อยแค่ไหน และช่วยตรวจสอบว่า Features มี Scale ต่างกันมากหรือไม่

np.float64(25.81988897471611)

In [32]:
x.var() # ใช้วัดความแปรปรวนของข้อมูล ถ้า Variance ต่ำมาก Feature นั้นอาจแทบไม่มีการเปลี่ยนแปลง

np.float64(666.6666666666666)

In [34]:
x.min() # ใช้ตรวจสอบค่าต่ำสุดและช่วงของ Feature

np.int64(10)

In [35]:
x.max()  # ใช้ตรวจสอบค่าสูงสุดของข้อมูล และช่วยสังเกตค่าที่อาจผิดปกติ

np.int64(90)

In [37]:
x.sum() # หาผลรวมของค่าทั้งหมด หรือเป็นส่วนหนึ่งของการคำนวณทางคณิตศาสตร์

np.int64(450)

In [40]:
x.argmin() # คืนตำแหน่งของค่าที่ต่ำที่สุด เพื่อใช้ดูว่าค่าต่ำสุดอยู่ที่ Sample ไหน

np.int64(0)

In [49]:
x.argmax() # คืนตำแหน่งของค่าที่สูงที่สุด ใช้บ่อยในการหา Class ที่มี Score หรือ Probability สูงที่สุด

np.int64(8)

In [53]:
x.mean(axis=0) # # Summary by columns ใช้หาค่าเฉลี่ยของแต่ละ Feature โดย Columns มักแทน Features

array([40., 50., 60.])

In [55]:
x.mean(axis=1) # Summary by rows # ใช้หาค่าสรุปของแต่ละ Sample

array([20., 50., 80.])