## Import NumPy Library

NumPy is a Python library for working with numerical data, Arrays, Vectors, and Matrices.

In Machine Learning, NumPy is commonly used to prepare numerical data and perform mathematical operations efficiently.

In [45]:
import numpy as np
from scipy import stats

## Creating Arrays

Arrays are one of the basic data structures used in numerical computing.

In Machine Learning, Arrays can be used to store **Features, Targets, Predictions, or Model Parameters**.

The examples below show common ways to create Arrays with NumPy.

### Common ways to create Arrays

`np.zeros()`, `np.ones()`, and `np.full()` are useful when we want to create an Array with a known starting value.

`np.array()` converts existing Python data into a NumPy Array.

`np.arange()` and `np.linspace()` are useful when we want NumPy to generate a sequence of numbers for us.

In [21]:
np.zeros(10) # Create an Array with 10 values initialized to 0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.ones(10) # Create an Array with 10 values, all set to 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.full(10, 2.5) # Create an Array with 10 values, all set to 2.5

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [24]:
a = np.array([1, 2, 3, 5, 7, 12]) # Convert a Python List into a NumPy Array
a # Display Array a

array([ 1,  2,  3,  5,  7, 12])

In [25]:
np.arange(3, 10) # Create a sequence of numbers from 3 to 9

array([3, 4, 5, 6, 7, 8, 9])

In [26]:
np.linspace(0, 100, 11) # Create 11 evenly spaced values from 0 to 100

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-Dimensional Arrays

A multi-dimensional Array can be used to represent a **Matrix**.

In Machine Learning, a Matrix is often similar to a Dataset or DataFrame:

- **Rows = Samples / Observations**
- **Columns = Features**

This is an important structure because Machine Learning data is commonly represented as a Feature Matrix.

### Reading a Matrix

For a 2D Matrix, NumPy uses the format:

`matrix[row, column]`

This lets us select one value, one Row, or one Column. In Machine Learning, this is useful when we want to work with a specific Sample or Feature.

In [24]:
np.zeros((5, 2)) # Create a Matrix with 5 Rows and 2 Columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]) # Create a 2D Matrix with 3 Rows and 3 Columns

n # Display Matrix n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
n[0, 1] = 20 # Select Row 1, Column 2 and change the value from 2 to 20

n # Display the updated Matrix

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [37]:
n[2] = [1, 1, 1] # Replace all values in Row 3 with 1

n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  1]])

In [36]:
n[:, 2] = [0, 1, 2] # Replace the values in Column 3

n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Randomly Generated Arrays

Random Arrays are useful for creating sample data for experiments and testing code.

In Machine Learning, random values may also be used when testing Algorithms, creating simulated data, or initializing values.

Using a **random seed** makes the random results reproducible, which means the same code can generate the same random values again.

### Why reproducibility matters

Machine Learning experiments often use random values. If the random values change every time we run the code, it can be difficult to compare results.

`np.random.seed()` fixes the random starting point so that the same experiment can be repeated.

In [3]:
np.random.seed(2) # Make the random result reproducible
100 * np.random.rand(5, 2) # Create random decimal values in a 5 x 2 Matrix

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [4]:
np.random.seed(2)
np.random.randn(5, 2) # Create random values from a Normal Distribution

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [5]:
np.random.seed(5)
np.random.randint(low=0, high=100, size=(5, 2)) # Create random integers from 0 to 99 in a 5 x 2 Matrix

array([[99, 78],
       [61, 16],
       [73,  8],
       [62, 27],
       [30, 80]])

## Element-wise Operations

Element-wise Operations apply the same calculation to every element in an Array.

Instead of writing a Loop and calculating one value at a time, NumPy can calculate all values at once.

In Machine Learning, this is useful for transforming Features, scaling values, and performing mathematical calculations efficiently.

### Why element-wise operations matter

Machine Learning often requires the same transformation to be applied to many data values.

NumPy performs this directly on Arrays, which is usually simpler and faster than processing each value separately with a Python Loop.

In [6]:
a = np.arange(5) # Create an Array: [0, 1, 2, 3, 4]
a

array([0, 1, 2, 3, 4])

In [7]:
b = (10 + (a * 2)) ** 2 / 100 # Apply the calculation to every element in Array a
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [8]:
a / b + 10 # Another example of element-wise calculation

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

## Comparison Operations

Comparison Operations check each value in an Array against a condition.

The result is usually a Boolean value:

- `True` = the condition is satisfied
- `False` = the condition is not satisfied

In Machine Learning and Data Analysis, comparison operations are useful for **filtering data, applying thresholds, and selecting specific values**.

### Boolean filtering

A comparison creates a Boolean Array. We can then use that Boolean Array to keep only values that match the condition.

This idea is widely used in Data Preparation and Data Cleaning.

In [18]:
print(a)
print(b)
a >= 2 # Check which values in Array a are greater than or equal to 2

[0 1 2 3 4]
[1.   1.44 1.96 2.56 3.24]


array([False, False,  True,  True,  True])

In [17]:
print(a)
print(b)
a > b # Compare Array a and Array b element by element

[0 1 2 3 4]
[1.   1.44 1.96 2.56 3.24]


array([False, False,  True,  True,  True])

In [16]:
print('a', a)
print('b', b)
a[a > b] # Return only values from a where the condition a > b is True

a [0 1 2 3 4]
b [1.   1.44 1.96 2.56 3.24]


array([2, 3, 4])

## Summarizing Operations

Summarizing Operations help us understand the overall characteristics of an Array or Matrix without looking at every value individually.

In Machine Learning, these operations are useful during **Data Understanding and Exploratory Data Analysis (EDA)**. They help us understand the center, spread, range, and overall behavior of Features before training a Model.

### Main groups

- **Central Tendency** → Mean, Median, Mode
- **Data Spread** → Standard Deviation, Variance
- **Range** → Minimum, Maximum
- **Aggregation** → Sum
- **Position** → Argmin, Argmax
- **Summarizing by Axis** → Summarize by Columns or Rows

### Why summarizing data matters

Before training a Model, we usually want to understand the data first.

For example:

- **Mean / Median / Mode** help describe typical values.
- **Standard Deviation / Variance** show how much the data changes.
- **Min / Max** show the range of values.
- **Argmin / Argmax** show where extreme values are located.
- **Axis operations** allow us to summarize each Feature or each Sample separately.

In [20]:
x = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

x # Example Matrix used for summarizing operations

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [43]:
x.mean() # Mean: calculate the average value of the data

np.float64(50.0)

In [28]:
np.median(x) # Median: find the middle value after ordering the data

np.float64(50.0)

In [47]:
stats.mode(x, axis=None) # Mode: find the value that occurs most often

ModeResult(mode=array([10, 20, 30]), count=array([1, 1, 1]))

In [30]:
x.std() # Standard Deviation: measure how far values spread from the Mean

np.float64(25.81988897471611)

In [32]:
x.var() # Variance: measure how much the values vary

np.float64(666.6666666666666)

In [34]:
x.min() # Minimum: find the smallest value

np.int64(10)

In [35]:
x.max() # Maximum: find the largest value

np.int64(90)

In [37]:
x.sum() # Sum: add all values together

np.int64(450)

In [40]:
x.argmin() # Argmin: return the position of the smallest value

np.int64(0)

In [49]:
x.argmax() # Argmax: return the position of the largest value

np.int64(8)

In [53]:
x.mean(axis=0) # Column summary: calculate the Mean of each Feature

array([40., 50., 60.])

In [55]:
x.mean(axis=1) # Row summary: calculate the Mean of each Sample

array([20., 50., 80.])